//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YY.EventLogExportAssistant.PostgreSQL {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YY.EventLogExportAssistant.PostgreSQL.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CREATE OR REPLACE VIEW vw_EventLog
        ///AS
        ///SELECT
        ///    &quot;RD&quot;.&quot;InformationSystemId&quot; AS &quot;InformationSystemId&quot;,
        ///    &quot;IS&quot;.&quot;Name&quot; AS &quot;InformationSystemName&quot;,
        ///    &quot;RD&quot;.&quot;Period&quot;,
        ///    &quot;RD&quot;.&quot;Id&quot; AS &quot;RowId&quot;,
        ///    &quot;RD&quot;.&quot;SeverityId&quot; AS &quot;SeverityId&quot;,
        ///    &quot;SV&quot;.&quot;Name&quot; AS &quot;SeverityName&quot;,
        ///    &quot;RD&quot;.&quot;ConnectId&quot; AS &quot;Connection&quot;,
        ///    &quot;RD&quot;.&quot;Session&quot;,
        ///    &quot;RD&quot;.&quot;TransactionStatusId&quot;,
        ///    &quot;RD&quot;.&quot;TransactionDate&quot;,
        ///    &quot;RD&quot;.&quot;TransactionId&quot;,
        ///    &quot;RD&quot;.&quot;UserId&quot; AS &quot;UserId&quot;,
        ///    &quot;USR&quot;.&quot;Name&quot; AS &quot;UserName&quot;,
        ///    &quot;USR&quot;.&quot;Uuid&quot; AS &quot;Use [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Query_CreateView_vw_EventLog {
            get {
                return ResourceManager.GetString("Query_CreateView_vw_EventLog", resourceCulture);
            }
        }
    }
}
