// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YY.EventLogExportAssistant.SQLServer;

namespace YY.EventLogExportAssistant.SQLServer.Migrations
{
    [DbContext(typeof(EventLogContext))]
    [Migration("20200507044912_Initialization")]
    partial class Initialization
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("YY.EventLogExportAssistant.SQLServer.Models.Applications", b =>
                {
                    b.Property<long>("InformationSystemId")
                        .HasColumnType("bigint");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("InformationSystemId", "Id");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("YY.EventLogExportAssistant.SQLServer.Models.Computers", b =>
                {
                    b.Property<long>("InformationSystemId")
                        .HasColumnType("bigint");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("InformationSystemId", "Id");

                    b.ToTable("Computers");
                });

            modelBuilder.Entity("YY.EventLogExportAssistant.SQLServer.Models.Events", b =>
                {
                    b.Property<long>("InformationSystemId")
                        .HasColumnType("bigint");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("InformationSystemId", "Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("YY.EventLogExportAssistant.SQLServer.Models.InformationSystems", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("InformationSystems");
                });

            modelBuilder.Entity("YY.EventLogExportAssistant.SQLServer.Models.LogFiles", b =>
                {
                    b.Property<long>("InformationSystemId")
                        .HasColumnType("bigint");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LastCurrentFileData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastCurrentFileReferences")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("LastEventNumber")
                        .HasColumnType("bigint");

                    b.Property<long>("LastStreamPosition")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("InformationSystemId", "FileName", "CreateDate", "Id");

                    b.ToTable("LogFiles");
                });

            modelBuilder.Entity("YY.EventLogExportAssistant.SQLServer.Models.Metadata", b =>
                {
                    b.Property<long>("InformationSystemId")
                        .HasColumnType("bigint");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("InformationSystemId", "Id");

                    b.ToTable("Metadata");
                });

            modelBuilder.Entity("YY.EventLogExportAssistant.SQLServer.Models.PrimaryPorts", b =>
                {
                    b.Property<long>("InformationSystemId")
                        .HasColumnType("bigint");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("InformationSystemId", "Id");

                    b.ToTable("PrimaryPorts");
                });

            modelBuilder.Entity("YY.EventLogExportAssistant.SQLServer.Models.RowData", b =>
                {
                    b.Property<long>("InformationSystemId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("Period")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("ApplicationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ComputerId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ConnectId")
                        .HasColumnType("bigint");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataPresentation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataUUID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("EventId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MetadataId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PrimaryPortId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SecondaryPortId")
                        .HasColumnType("bigint");

                    b.Property<long?>("Session")
                        .HasColumnType("bigint");

                    b.Property<long?>("SeverityId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("TransactionId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TransactionStatusId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("WorkServerId")
                        .HasColumnType("bigint");

                    b.HasKey("InformationSystemId", "Period", "Id");

                    b.ToTable("RowsData");
                });

            modelBuilder.Entity("YY.EventLogExportAssistant.SQLServer.Models.SecondaryPorts", b =>
                {
                    b.Property<long>("InformationSystemId")
                        .HasColumnType("bigint");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("InformationSystemId", "Id");

                    b.ToTable("SecondaryPorts");
                });

            modelBuilder.Entity("YY.EventLogExportAssistant.SQLServer.Models.Severities", b =>
                {
                    b.Property<long>("InformationSystemId")
                        .HasColumnType("bigint");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("InformationSystemId", "Id");

                    b.ToTable("Severities");
                });

            modelBuilder.Entity("YY.EventLogExportAssistant.SQLServer.Models.TransactionStatuses", b =>
                {
                    b.Property<long>("InformationSystemId")
                        .HasColumnType("bigint");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("InformationSystemId", "Id");

                    b.ToTable("TransactionStatuses");
                });

            modelBuilder.Entity("YY.EventLogExportAssistant.SQLServer.Models.Users", b =>
                {
                    b.Property<long>("InformationSystemId")
                        .HasColumnType("bigint");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("InformationSystemId", "Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("YY.EventLogExportAssistant.SQLServer.Models.WorkServers", b =>
                {
                    b.Property<long>("InformationSystemId")
                        .HasColumnType("bigint");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("InformationSystemId", "Id");

                    b.ToTable("WorkServers");
                });
#pragma warning restore 612, 618
        }
    }
}
